### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by odesh009** [victorgz/vscode-snippets-for-salesforce#3]
- Issue Type: `Bug`
- Extension Name: `snippets-for-salesforce-devs`
- Extension Version: `2.0.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.1`

I tries all the possible ways to add a class, method and other comments but its not working.
I tries changing the prefix to !! !!Doc **** but comment snippets are not working

**Comment by victorgz** [comment]
Hi @odesh009 ,

Have you tried restarting VSCode after you define the prefix in the settings? The extension loads the configuration when it is initalized and there is no settings sync for now.

**Comment by odesh009** [comment]
@victorgz Yes i tried restarting VSCode but its not working. I did everything. reinstalled VSCode but still the issue is there. Is there anything like local config file which i have to delete

**Comment by victorgz** [comment]
@odesh009 no, there is nothing you might have to delete or to change locally. The only potential reason that I have in mind could be a problem when retrieving your git configuration (user.email and user.name). Nowadays the extension is silently ignoring errors if your git configuration is not retrieved correctly, there is no mechanism in place to handle and expose them to the user.

I would suggest you to review that point. I will include this in my backlog, but for information, there is no roadmap defined yet for fixes and new features for this extension.
